---
title: "Data Description"
author: "Josef Mana"
date: "`r Sys.Date()`"
number-sections: true
format:
  html:
    self-contained: true
    title-block-banner: true
    toc: true
    warning: false
    code-fold: true
    df-print: kable
  pdf:
    echo: false
    warning: false
    df-print: kable
---

```{r}
#| label: import
#| warning: false

rm( list = ls() )

# packages to use
library(here)
library(dplyr)
library(tidyverse)
library(gt)

# read the data
d0 <- read.csv( here("_data","desc.csv"), sep = "," ) # demographic and clinical variables
d1 <- read.csv( here("_data","ssrt_lab.csv"), sep = "," ) # SSRT data
v <- read.csv( here("_data","vars.csv"), sep = ";" ) # variable names and groupings

# some in-house functions
rprint <- function( x, dec = 2 ) sprintf( paste0("%.",dec,"f"), round( x, dec ) )

```

This is a report providing descriptive statistics of `r nrow(d0)` patients included in the experiment of combined (mid/high) stimulation to (ventral/dorsal) STN for cognitive intervention in PD.

## Demographics

```{r}
#| label: tbl-desc
#| tbl-cap: Patient-specific information
#| column: page-inset-right

d0 %>%
  mutate( across( where(is.numeric), ~ sub( ".00", "", rprint(.x,2), fixed = T ) ) ) %>%
  column_to_rownames("id") %>%
  t() %>%
  as.data.frame() %>%
  mutate( across( everything(), ~ ifelse( grepl("NA",.x), "-", .x ) ) ) %>%
  rownames_to_column("var") %>%
    mutate(
        grp = sapply( 1:nrow(.), function(i) v[ v$var == var[i], "grp" ] ),
        var = sapply( 1:nrow(.), function(i) v[ v$var == var[i], "lab" ] )
    ) %>%
    gt( rowname_col = "var", groupname_col = "grp" ) %>%
    cols_align( align = "center", columns = -1 )
```


```{r}
#| label: tbl-ssrt
#| tbl-cap: "Patient-specific task outcomes' summaries"
#| column: page-inset-right

# using table "t" from "ssrt_desc.R" run this:
gt( t, rowname_col = "var", groupname_col = "type" ) %>%
    
  # need to more efficient way to do this
  tab_spanner( label = "IPN275", columns = starts_with("IPN275"), gather = F ) %>%
  tab_spanner( label = "IPN285", columns = starts_with("IPN285"), gather = F ) %>%
  tab_spanner( label = "IPN390", columns = starts_with("IPN390"), gather = F ) %>%
  tab_spanner( label = "IPN526", columns = starts_with("IPN526"), gather = F ) %>%
  tab_spanner( label = "IPN541", columns = starts_with("IPN541"), gather = F ) %>%
  tab_spanner( label = "IPN601", columns = starts_with("IPN601"), gather = F ) %>%
  tab_spanner( label = "IPN602", columns = starts_with("IPN602"), gather = F ) %>%
  tab_spanner( label = "IPN715", columns = starts_with("IPN715"), gather = F ) %>%
    
  tab_spanner( label = "0+", columns = contains("0+"), gather = F ) %>%
  tab_spanner( label = "+0", columns = contains("+0"), gather = F ) %>%
    
  cols_label(
    ends_with("ctrl") ~ "0",
    ends_with("exp") ~ "+"
  ) %>%
    
  cols_align( -1, align = "center" )
```